name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set pull request number
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        run: echo "PULL_REQUEST_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
      - name: Test Endpoint
        run: |
          curl -X POST -H "Content-Type: application/json" -d {"pull_request_number": "${{ env.PULL_REQUEST_NUMBER }}"} https://35bd-23-112-11-217.ngrok-free.app/review_build_error_logs