name: GitHub Actions Setup

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send pull request number to endpoint
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST -H "Content-Type: application/json" -d "{\"pull_request_number\": \"$PR_NUMBER\"}" https://35bd-23-112-11-217.ngrok-free.app/review_build_error_logs
