name: CI

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test endpoint
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"pull_request_number": ${{ github.event.pull_request.number }}}' https:/f900-23-112-11-217.ngrok-free.app/test
